<!DOCTYPE html>
<html lang=en-US>
<head>
<meta charset=utf-8>
<title>Linux command close</title><meta name="description" content="Linux command close close a file descriptor"><meta name="keywords" content="linux, command, close, bsd, close a file descriptor"><meta name="robots" content="index,follow">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container">

<h1>NAME</h1>
<p>close - close a file descriptor</p>
<h1>SYNOPSIS</h1>
<pre><code>#include &lt;unistd.h&gt;

int close(int fd);</code></pre>
<h1>DESCRIPTION</h1>
<p><strong>close</strong>() closes a file descriptor, so that it no longer refers to any file and may be reused. Any record locks (see <strong>fcntl</strong>(2)) held on the file it was associated with, and owned by the process, are removed (regardless of the file descriptor that was used to obtain the lock).</p>
<p>If <em>fd</em> is the last file descriptor referring to the underlying open file description (see <strong>open</strong>(2)), the resources associated with the open file description are freed; if the file descriptor was the last reference to a file which has been removed using <strong>unlink</strong>(2), the file is deleted.</p>
<h1>RETURN VALUE</h1>
<p><strong>close</strong>() returns zero on success. On error, -1 is returned, and <em>errno</em> is set appropriately.</p>
<h1>ERRORS</h1>
<dl>
<dt><strong>EBADF</strong></dt>
<dd><p><em>fd</em> isn't a valid open file descriptor.</p>
</dd>
<dt><strong>EINTR</strong></dt>
<dd><p>The <strong>close</strong>() call was interrupted by a signal; see <strong>signal</strong>(7).</p>
</dd>
<dt><strong>EIO</strong></dt>
<dd><p>An I/O error occurred.</p>
</dd>
<dt><strong>ENOSPC</strong>, <strong>EDQUOT</strong></dt>
<dd><p>On NFS, these errors are not normally reported against the first write which exceeds the available storage space, but instead against a subsequent <strong>write</strong>(2), <strong>fsync</strong>(2), or <strong>close</strong>().</p>
</dd>
</dl>
<p>See NOTES for a discussion of why <strong>close</strong>() should not be retried after an error.</p>
<h1>CONFORMING TO</h1>
<p>POSIX.1-2001, POSIX.1-2008, SVr4, 4.3BSD.</p>
<h1>NOTES</h1>
<p>A successful close does not guarantee that the data has been successfully saved to disk, as the kernel uses the buffer cache to defer writes. Typically, filesystems do not flush buffers when a file is closed. If you need to be sure that the data is physically stored on the underlying disk, use <strong>fsync</strong>(2). (It will depend on the disk hardware at this point.)</p>
<p>The close-on-exec file descriptor flag can be used to ensure that a file descriptor is automatically closed upon a successful <strong>execve</strong>(2); see <strong>fcntl</strong>(2) for details.</p>
<h2>Multithreaded processes and close()</h2>
<p>It is probably unwise to close file descriptors while they may be in use by system calls in other threads in the same process. Since a file descriptor may be reused, there are some obscure race conditions that may cause unintended side effects.</p>
<p>Furthermore, consider the following scenario where two threads are performing operations on the same file descriptor:</p>
<ol type="1">
<li><p>One thread is blocked in an I/O system call on the file descriptor. For example, it is trying to <strong>write</strong>(2) to a pipe that is already full, or trying to <strong>read</strong>(2) from a stream socket which currently has no available data.</p></li>
<li><p>Another thread closes the file descriptor.</p></li>
</ol>
<p>The behavior in this situation varies across systems. On some systems, when the file descriptor is closed, the blocking system call returns immediately with an error.</p>
<p>On Linux (and possibly some other systems), the behavior is different. the blocking I/O system call holds a reference to the underlying open file description, and this reference keeps the description open until the I/O system call completes. (See <strong>open</strong>(2) for a discussion of open file descriptions.) Thus, the blocking system call in the first thread may successfully complete after the <strong>close</strong>() in the second thread.</p>
<h2>Dealing with error returns from close()</h2>
<p>A careful programmer will check the return value of <strong>close</strong>(), since it is quite possible that errors on a previous <strong>write</strong>(2) operation are reported only on the final <strong>close</strong>() that releases the open file description. Failing to check the return value when closing a file may lead to <em>silent</em> loss of data. This can especially be observed with NFS and with disk quota.</p>
<p>Note, however, that a failure return should be used only for diagnostic purposes (i.e., a warning to the application that there may still be I/O pending or there may have been failed I/O) or remedial purposes (e.g., writing the file once more or creating a backup).</p>
<p>Retrying the <strong>close</strong>() after a failure return is the wrong thing to do, since this may cause a reused file descriptor from another thread to be closed. This can occur because the Linux kernel <em>always</em> releases the file descriptor early in the close operation, freeing it for reuse; the steps that may return an error, such as flushing data to the filesystem or device, occur only later in the close operation.</p>
<p>Many other implementations similarly always close the file descriptor (except in the case of <strong>EBADF</strong>, meaning that the file descriptor was invalid) even if they subsequently report an error on return from <strong>close</strong>(). POSIX.1 is currently silent on this point, but there are plans to mandate this behavior in the next major release of the standard.</p>
<p>A careful programmer who wants to know about I/O errors may precede <strong>close</strong>() with a call to <strong>fsync</strong>(2).</p>
<p>The <strong>EINTR</strong> error is a somewhat special case. Regarding the <strong>EINTR</strong> error, POSIX.1-2008 says:</p>
<blockquote>
<p>If <strong>close</strong>() is interrupted by a signal that is to be caught, it shall return -1 with <em>errno</em> set to <strong>EINTR</strong> and the state of <em>fildes</em> is unspecified.</p>
</blockquote>
<p>This permits the behavior that occurs on Linux and many other implementations, where, as with other errors that may be reported by <strong>close</strong>(), the file descriptor is guaranteed to be closed. However, it also permits another possibility: that the implementation returns an <strong>EINTR</strong> error and keeps the file descriptor open. (According to its documentation, HP-UX's <strong>close</strong>() does this.) The caller must then once more use <strong>close</strong>() to close the file descriptor, to avoid file descriptor leaks. This divergence in implementation behaviors provides a difficult hurdle for portable applications, since on many implementations, <strong>close</strong>() must not be called again after an <strong>EINTR</strong> error, and on at least one, <strong>close</strong>() must be called again. There are plans to address this conundrum for the next major release of the POSIX.1 standard.</p>
<h1>SEE ALSO</h1>
<p><strong>fcntl</strong>(2), <strong>fsync</strong>(2), <strong>open</strong>(2), <strong>shutdown</strong>(2), <strong>unlink</strong>(2), <strong>fclose</strong>(3)</p>
<h1>COLOPHON</h1>
<p>This page is part of release 5.10 of the Linux <em>man-pages</em> project. A description of the project, information about reporting bugs, and the latest version of this page, can be found at https://www.kernel.org/doc/man-pages/.</p>
<footer style="text-align: center;"><a href="https://blog.tamer.pw" target="_blank">Blog</a> | <a href="https://github.com/linuxtamer" target="_blank">Contact</a></footer>
</div>
</body>
</html>

